AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.2
  SuggestExtensions: false

Metrics/BlockLength:
  CountComments: false
  Max: 100
  AllowedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

